# Generated by Django 5.2.13 on 2026-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('lux', 'Люкс')], default='standard', max_length=20, verbose_name='Тип комнаты')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['number'],
            },
        ),
    ]
