# Generated by Django 5.2.11 on 2026-04-19 08:48

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="images",
            field=models.ImageField(default=None, upload_to=""),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.CreateModel(
            name="AccountInfo",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="info",
                        serialize=False,
                        to="rooms.account",
                        verbose_name="Аккаунт",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[users.validators.real_number],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        unique=True,
                        validators=[users.validators.real_email],
                        verbose_name="Почта",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_date",
                    models.DateField(blank=True, verbose_name="Дата начала брони"),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=None, null=None, verbose_name="Дата окончания брони"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sleeping", "Ожидает"),
                            ("active", "Активна"),
                            ("dead", "Завершена"),
                        ],
                        default="sleeping",
                        max_length=15,
                        verbose_name="Статус брони",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="rooms.account",
                        verbose_name="Клиент",
                    ),
                ),
            ],
        ),
    ]
