# Generated by Django 5.2.11 on 2026-04-20 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_account_room_images_alter_room_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
