# Generated by Django 5.2.11 on 2026-04-21 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_booking_client"),
        ("rooms", "0003_delete_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountinfo",
            name="account",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="AccountInfo",
        ),
    ]
