# Generated by Django 5.2.11 on 2026-04-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0003_delete_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_date",
                    models.DateField(blank=True, verbose_name="Дата начала брони"),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=None, null=None, verbose_name="Дата окончания брони"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sleeping", "Ожидает"),
                            ("active", "Активна"),
                            ("dead", "Завершена"),
                        ],
                        default="sleeping",
                        max_length=15,
                        verbose_name="Статус брони",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="rooms.account",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="rooms.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
        ),
    ]
