# Generated by Django 5.2.11 on 2026-05-06 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_booking_client"),
        ("rooms", "0004_remove_accountinfo_account_delete_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="filler", max_length=100, verbose_name="Название услуги"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="rooms.room",
                verbose_name="Комната",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="servises",
            field=models.ManyToManyField(
                null=True,
                related_name="services",
                to="booking.services",
                verbose_name="Услуги",
            ),
        ),
    ]
