# Generated by Django 5.2.11 on 2026-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_services_alter_booking_client_alter_booking_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="servises",
            field=models.ManyToManyField(
                related_name="services", to="booking.services", verbose_name="Услуги"
            ),
        ),
    ]
