# Generated by Django 5.2.11 on 2026-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_booking_servises"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="cost",
            field=models.IntegerField(
                default=0, max_length=20, verbose_name="Стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название услуги"
            ),
        ),
    ]
