# Generated by Django 5.2.11 on 2026-04-21 08:07

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountInfo",
            fields=[
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аккаунт",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[users.validators.real_number],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        unique=True,
                        validators=[users.validators.real_email],
                        verbose_name="Почта",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
            ],
        ),
    ]
